server:
  port: 8700
spring:
  application:
    name: admin-server

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/

security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
