spring:
  application:
    name: service-consumer

server:
  port: 8091

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:8761/eureka/
  instance:
      instance-id:  ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}